<?php

use Drupal\Core\Site\Settings;

/**
 * Implements hook_library_info_build().
 */
function vite_library_info_build() {
  $libraries = [];

  // Production directory.
  $dir = 'dist';

  // Local development with Vite
  if (Settings::get('hot_module_replacement')) {
    $dir = 'http://localhost:12321';
    $css_options = [
      'type' => 'external',
    ];
    $js_options = [
      'type' => 'external',
      'attributes' => [
        'type' => 'module',
        'crossorigin' => TRUE,
      ],
    ];

    // Add a library whose information changes depending on certain conditions.
    $libraries['hot-module-replacement'] = [
      'js' => [
        "${dir}/@vite/client" => $js_options,
      ],
    ];

    $libraries['global-styling'] = [
      'css' => [
        'theme' => [
          "${dir}/scss/styles.scss" => $css_options,
        ]
      ],
      'js' => [
        "${dir}/js/main.js" => $js_options,
      ],
      'dependencies' => [
        'core/jquery'
      ]
    ];
  }

  return $libraries;
}
